### ISSUE TITLE
[Bug]: PayPal REST API list plans fails with internal server error for more than 10 days

### ISSUE THREAD

**Issue by 8ctopus** [paypal-examples/paypal-dev-support#7]
### Contact Details

hello@octopuslabs.io

### Describe the Issue

REST API provides curl exampleto list all existing plans:

https://developer.paypal.com/docs/api/subscriptions/v1/#plans_list

Unfortunately the request doesn't work for more than 10 days. Here's what I get:

```sh
$ curl -v -X GET "https://api-m.sandbox.paypal.com/v1/billing/plans?sort_by=create_time&sort_order=desc" \
-H 'Authorization: Bearer TOKEN_RETRACTED' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Prefer: return=representation'
Note: Unnecessary use of -X or --request, GET is already inferred.
* processing: https://api-m.sandbox.paypal.com/v1/billing/plans?sort_by=create_time&sort_order=desc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 146.75.117.35:443...
* Connected to api-m.sandbox.paypal.com (146.75.117.35) port 443
* schannel: disabled automatic use of client certificate
* using HTTP/1.x
> GET /v1/billing/plans?sort_by=create_time&sort_order=desc HTTP/1.1
> Host: api-m.sandbox.paypal.com
> User-Agent: curl/8.2.1
> Authorization: Bearer TOKEN_RETRACTED
> Content-Type: application/json
> Accept: application/json
> Prefer: return=representation
>
< HTTP/1.1 500 Internal Server Error
< Connection: keep-alive
< Content-Length: 233
< Content-Type: application/json
< Server: nginx
< Cache-Control: max-age=0, no-cache, no-store, must-revalidate
< Paypal-Debug-Id: 9330448c4803d
< X-Slr-Retry: 500
< X-Slr-Retry-Api: /v1/billing/plans
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Edge-Control: max-age=0
< Accept-Ranges: bytes
< Date: Fri, 15 Sep 2023 09:44:32 GMT
< Via: 1.1 varnish
< X-Served-By: cache-fra-eddf8230025-FRA
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1694771072.216580,VS0,VE491
< Vary: Accept-Encoding
<
{ [233 bytes data]
100   233  100   233    0     0    202      0  0:00:01  0:00:01 --:--:--   202{"name":"INTERNAL_SERVER_ERROR","message":"An internal server error has occurred.","debug_id":"9330448c4803d","details":[{"issue":"INTERNAL_ERROR","description":"TaskExecutor Reactor Task : CHECKPOINT_FETCH_PLAN Failed"}],"links":[]}
* Connection #0 to host api-m.sandbox.paypal.com left intact
```

### Steps To Reproduce

See above

### What type of Operating System are you seeing the problem on?

Windows

### What type of browser are you seeing the problem on?

N/A

### Screenshots or Videos

N/A

### Code to produce this issue.

```shell
$ curl -v -X GET "https://api-m.sandbox.paypal.com/v1/billing/plans?sort_by=create_time&sort_order=desc" \
-H 'Authorization: Bearer TOKEN_RETRACTED' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Prefer: return=representation'
```

**Comment by devchristina** [comment]
Hi @8ctopus -- apologize for the delay. I acknowledge this issue and am working to get the right team engaged.

**Comment by devchristina** [comment]
@8ctopus -- We've confirmed that this is a reproducible issue and have submitted a bug ticket to the engineering team. We'll circle back once we know more about delivery.

**Comment by 8ctopus** [comment]
@devchristina Thank you for looking into it.
I'll report more bugs since you acknowledged this one. Found a lot of them actually.

**Comment by devchristina** [comment]
Sounds like a plan! Thank you.

**Comment by anant-pypl** [comment]
@8ctopus 
There was a bug fixed. Please delete the billing plans and re-create them.
Please let us know if this actions solves this problem, then we can close the internal issue on our end.
Thanks!

**Comment by 8ctopus** [comment]
@anant-pypl How do you delete a plan? I was also looking for it but it seems the only possibility is to disable a plan (at least according to the documentation):

https://developer.paypal.com/docs/api/subscriptions/v1/#plans_deactivate

**Comment by devchristina** [comment]
@8ctopus - You're correct in your assumption, you may only disable a plan. You cannot delete (by definition) a plan.

**Comment by 8ctopus** [comment]
@devchristina Listing plans still provokes the same internal error.

**Comment by anant-pypl** [comment]
There are two options to cancel plan
1. Check that plan on merchant dashboard and deactivate from there directly.
2. Use deactivate api:  https://developer.paypal.com/docs/api/subscriptions/v1/#plans_deactivate

**Comment by cnallam** [comment]
@8ctopus I just tried to list-plans API using postman it is working as expected. I didn't see any errors. 
Are you getting this error every time or  intermittent?
Can you let us know reproducible steps, if still you are facing it?

**Comment by 8ctopus** [comment]
@cnallam I'm still having the same problem and I'm getting the error every time.
I'm not doing anything special. I'm just trying to list the plans:

```sh
curl -v -X GET "https://api-m.sandbox.paypal.com/v1/billing/plans?sort_by=create_time&sort_order=desc" \
-H 'Authorization: Bearer A21AAKuLBvunbDOHrhux5jY8QEJWnSYXPBir9Sujh9fD4XIv2J0vTQslAvDJN0pmj80geoSTUNfRg1M5AJuKHTUZ5blgoBs0w' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Prefer: return=representation'
```

```json
{
    "name": "INTERNAL_SERVER_ERROR",
    "message": "An internal server error has occurred.",
    "debug_id": "2343a07028b14",
    "details": [
        {
            "issue": "INTERNAL_ERROR",
            "description": "TaskExecutor Reactor Task : CHECKPOINT_FETCH_PLAN Failed"
        }
    ],
    "links": []
}
```

**Comment by 8ctopus** [comment]
@anant-pypl I did deactivate all plans that I remember of (as I cannot get the full list) and then tried to list the plans again, unfortunately without success.

**Comment by 8ctopus** [comment]
Also listing plans within the PayPal sandbox business account is not working with error `genericError`:

![paypal-plans](https://github.com/paypal-examples/paypal-dev-support/assets/13252042/d65cd2f1-748e-4f63-8c85-fc90096ae040)

**Comment by cnallam** [comment]
@8ctopus - Left a comment to the engineering team on the existing ticket to look in to this issue. 
If you are blocked with this issue, workaround might be: Setup new developer account and try creating new product and plan.

**Comment by 8ctopus** [comment]
@cnallam I have created a new business PayPal account under the developer account and with this account, I can: create a new plan and list plans. It works both in the GUI and using the REST API.

Last issue, I do not seem to be able to delete the default business account (that was created with the developer account).
